######################################################################
# Automatically generated by qmake (3.0) sön mars 18 21:11:15 2018
######################################################################

QT += testlib
TEMPLATE = app
TARGET = Test

CONFIG += link_pkgconfig
PKGCONFIG += openssl

INCLUDEPATH += . ..

# Input
SOURCES += test_encryptor.cpp ../encryptor.cpp

HEADERS += ../encryptor.h ../Private/encryptor_p.h
