######################################################################
# Automatically generated by qmake (3.0) sön mars 18 21:11:15 2018
######################################################################

QT += testlib
TEMPLATE = app
TARGET = Test

INCLUDEPATH += . ..

# Input
SOURCES += test_emojiparser.cpp \
    ../../emojispecparser.cpp

HEADERS += emojispecparser.h \
    ../../Private/emojispecparserprivate.h
