#ifndef CONFIG_FIELD_H
#define CONFIG_FIELD_H

#define WICHAT_SESNFRAME_FONT_STYLE_BOLD "bold"
#define WICHAT_SESNFRAME_FONT_STYLE_ITALIC "italic"
#define WICHAT_SESNFRAME_FONT_STYLE_UNDERLINE "underline"
#define WICHAT_SESNFRAME_FONT_STYLE_STRIKEOUT "strikeout"
#define WICHAT_SESNFRAME_FONT_STYLE_OVERLINE "overline"

#define WICHAT_SESNFRAME_TEXT_ALIGN_LEFT "left"
#define WICHAT_SESNFRAME_TEXT_ALIGN_CENTER "center"
#define WICHAT_SESNFRAME_TEXT_ALIGN_RIGHT "right"

#define WICHAT_SESNFRAME_EDITOR_SENDKEY_ENTER 0x01000004
#define WICHAT_SESNFRAME_EDITOR_SENDKEY_CTRLENTER 0x01000004 + 0x04000000

#endif // CONFIG_FIELD_H
